name: Conda Environment Setup

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge 
        python-version: 3.10  
        auto-update-conda: true
        activate-environment: myenv  
        environment-file: environment.yml  

    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name myenv
        conda activate myenv

    - name: Run Conda Info
      run: conda info

    - name: Run Conda List
      run: conda list
